name: Generate Org Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-org-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установить зависимости
        run: |
          sudo apt update && sudo apt install -y jq curl bc
      
      - name: Получить данные об организации и сгенерировать donut chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ORG="DiametrEDU"
          
          # 1. Получаем список репозиториев
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/$ORG/repos?per_page=100" > repos.json

          # 2. Собираем статистику по языкам
          declare -A languages
          total_bytes=0
          for repo in $(jq -r '.[].name' repos.json); do
            echo "Processing repo: $repo"
            repo_langs_json=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$ORG/$repo/languages")
            
            # Проверяем, не пустой ли JSON (например, для пустого репозитория)
            if [[ -z "$repo_langs_json" || "$repo_langs_json" == "{}" ]]; then
              continue
            fi

            for lang in $(echo "$repo_langs_json" | jq -r 'keys[]'); do
              bytes=$(echo "$repo_langs_json" | jq ".\"$lang\"")
              # --- ГЛАВНОЕ ИСПРАВЛЕНИЕ ---
              # Кавычки вокруг "$lang" обязательны для языков вроде C++ или C#
              ((languages["$lang"]+=$bytes))
              ((total_bytes+=$bytes))
            done
          done

          if [[ $total_bytes -eq 0 ]]; then
            echo "No language data found. Exiting."
            exit 0
          fi

          # 3. Сортируем языки по объему (от большего к меньшему)
          # Это сделает диаграмму и легенду более читаемыми и консистентными
          sorted_langs=()
          while IFS= read -r line; do
              # Извлекаем название языка из строки "РАЗМЕР НАЗВАНИЕ"
              sorted_langs+=("$(echo "$line" | cut -d' ' -f2-)")
          done < <(
              for lang in "${!languages[@]}"; do
                  printf "%d %s\n" "${languages[$lang]}" "$lang"
              done | sort -rn
          )

          # 4. Готовим SVG
          # Расширенная палитра цветов
          palette=("#e6194b" "#3cb44b" "#ffe119" "#4363d8" "#f58231" "#911eb4" "#46f0f0" "#f032e6" "#bcf60c" "#fabebe" "#008080" "#e6beff" "#9a6324" "#fffac8" "#800000" "#aaffc3" "#808000" "#ffd8b1" "#000075" "#808080")
          declare -A colors
          i=0
          for lang in "${sorted_langs[@]}"; do
            colors["$lang"]=${palette[$((i % ${#palette[@]}))]}
            ((i++))
          done

          # Функция для преобразования полярных координат в декартовы
          polar_to_cartesian() {
            local cx=$1 cy=$2 r=$3 angle=$4
            local rad=$(echo "$angle * 3.14159265 / 180" | bc -l)
            local x=$(echo "$cx + $r * c($rad)" | bc -l)
            local y=$(echo "$cy + $r * s($rad)" | bc -l)
            echo "$x $y"
          }

          # Начинаем создавать SVG файл
          svg_file="org-stats.svg"
          echo "<svg width=\"600\" height=\"300\" viewBox=\"0 0 600 300\" xmlns=\"http://www.w3.org/2000/svg\">" > "$svg_file"
          echo "  <style>text { font: 14px sans-serif; fill: #333; } .org-name { font-weight: bold; font-size: 16px; }</style>" >> "$svg_file"

          # Рисуем сектора "пончика"
          start_angle=0
          for lang in "${sorted_langs[@]}"; do
            percent=$(echo "scale=10; ${languages[$lang]} / $total_bytes" | bc)
            angle=$(echo "$percent * 360" | bc -l)
            # Пропускаем очень маленькие сектора, чтобы избежать ошибок с путями
            if (( $(echo "$angle < 0.1" | bc -l) )); then continue; fi

            end_angle=$(echo "$start_angle + $angle" | bc -l)
            read x1 y1 <<< $(polar_to_cartesian 150 150 100 $start_angle)
            read x2 y2 <<< $(polar_to_cartesian 150 150 100 $end_angle)
            large_arc=$(echo "$angle > 180" | bc)

            echo "  <path d=\"M150,150 L$x1,$y1 A100,100 0 $large_arc,1 $x2,$y2 Z\" fill=\"${colors[$lang]}\"/>" >> "$svg_file"
            start_angle=$end_angle
          done

          # Рисуем "дырку" в центре
          echo "  <circle cx=\"150\" cy=\"150\" r=\"60\" fill=\"white\"/>" >> "$svg_file"
          echo "  <text x=\"150\" y=\"150\" text-anchor=\"middle\" dominant-baseline=\"middle\" class=\"org-name\">$ORG</text>" >> "$svg_file"

          # Рисуем легенду
          legend_y=30
          for lang in "${sorted_langs[@]}"; do
            # Отображаем только языки, составляющие > 0.1%
            percent=$(echo "scale=2; ${languages[$lang]} * 100 / $total_bytes" | bc)
            if (( $(echo "$percent < 0.1" | bc -l) )); then continue; fi
            percent_display=$(printf "%.1f" "$percent")
            
            echo "  <rect x=\"320\" y=\"$legend_y\" width=\"12\" height=\"12\" fill=\"${colors[$lang]}\" />" >> "$svg_file"
            legend_text_y=$((legend_y + 11))
            echo "  <text x=\"340\" y=\"$legend_text_y\">$lang (${percent_display}%%)</text>" >> "$svg_file"
            legend_y=$((legend_y + 20))
            # Останавливаемся, если легенда становится слишком длинной
            if [[ $legend_y -gt 280 ]]; then
              echo "  <text x=\"340\" y=\"$legend_text_y\">...</text>" >> "$svg_file"
              break
            fi
          done
          
          echo "</svg>" >> "$svg_file"
          echo "SVG chart generated successfully."

      - name: Коммит и пуш SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add org-stats.svg
          # Проверяем, есть ли изменения перед коммитом
          if ! git diff --staged --quiet; then
            git commit -m "📊 Обновление статистики языков организации"
            git push
          else
            echo "Нет изменений для коммита."
          fi
