name: Generate Org Stats

on:
  # Запускаем раз в день в полночь
  schedule:
    - cron: '0 0 * * *'
  # Позволяет запускать вручную со страницы Actions
  workflow_dispatch:

jobs:
  build-org-stats:
    runs-on: ubuntu-latest
    steps:
      # Этот Action сгенерирует для нас красивый SVG файл со статистикой
      - uses: lowlighter/metrics@latest
        with:
          # Имя файла, который будет создан
          filename: org-stats.svg

          # Токен для доступа к API GitHub
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Указываем, что статистика нужна для организации, а не для пользователя
          user: DiametrEDU
          
          # Указываем, какие плагины (блоки статистики) мы хотим видеть
          # В данном случае, нам нужен только плагин с языками
          base: "" # Оставляем пустым, чтобы убрать базовые блоки
          plugins: |
            languages
            
          # Настройки для плагина языков
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming # Какие типы файлов считать
          plugin_languages_colors: github # Используем стандартные цвета GitHub для языков
          plugin_languages_limit: 8 # Показать 8 самых популярных языков
          plugin_languages_threshold: 0% # Показывать языки, даже если их процент мал
          plugin_languages_layout: compact # Компактный вид

      # Этот шаг нужен, чтобы закоммитить сгенерированный файл в репозиторий
      - name: Коммит и пуш SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Добавляем файл в отслеживаемые
          git add org-stats.svg
          # Создаем коммит, только если файл изменился
          if ! git diff --staged --quiet; then
            git commit -m "📊 Обновление статистики языков организации"
            git push
          else
            echo "Изменений в статистике нет, коммит не требуется."
          fi
