name: Generate Org Stats

on:
  schedule:
    - cron: '0 0 * * *' # Каждый день в полночь
  workflow_dispatch:

jobs:
  build-org-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установить зависимости
        run: |
          sudo apt update && sudo apt install -y jq curl

      - name: Получить данные об организации
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ORG="DiametrEDU"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/$ORG/repos?per_page=100" > repos.json

          # Собираем статистику по языкам
          declare -A languages
          for repo in $(jq -r '.[].name' repos.json); do
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$ORG/$repo/languages" > lang.json
            for lang in $(jq -r 'keys[]' lang.json); do
              bytes=$(jq ".\"$lang\"" lang.json)
              ((languages[$lang]+=$bytes))
            done
          done

          # Формируем SVG
          echo "<svg width=\"600\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\">" > org-stats.svg
          echo "<style>text { font: 14px sans-serif; }</style>" >> org-stats.svg
          echo "<text x=\"0\" y=\"15\">🌐 Языки DiametrEDU: " >> org-stats.svg

          X=160
          for lang in "${!languages[@]}"; do
            echo "<tspan dx=\"10\">$lang (${languages[$lang]} bytes)</tspan>" >> org-stats.svg
          done

          echo "</text></svg>" >> org-stats.svg

      - name: Коммит и пуш SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add org-stats.svg
          git commit -m "🔄 Обновление org-stats.svg (языки)" || echo "Нет изменений"
          git push
